[package]
name = "snake-game-terminal"
version = "0.1.0"
edition = "2024"

[dependencies]
approx = "0.5.1"
color-eyre = "0.6.5"
image = "0.25.9"
rand = { version = "0.9.2", features = ["os_rng"] }
ratatui = {version = "0.30.0", features=["termion"]}
ratatui-image = "10.0.2"
